In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from label_to_cat import LABEL_TO_CAT

BATCHES_COUNT = 12091

In [8]:
%%time
store1 = pd.HDFStore('../input/test_resnet.h5')
keys1 = store1.keys()
print('{} tables in storage'.format(len(keys1)))

1 tables in storage
CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 10.5 ms


In [9]:
t1 = store1.select('d0')
t1.head(10)

pr_id  img_num    1    2    3    4    5    6    7    8  ...   5261  5262  \
0     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
1     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
2     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
3     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
4     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
5     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
6     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
7     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
8     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   
9     14        0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   0.0   

   5263  5264  5265  5266  5267  5268  5269  5270  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[10 rows x 5272 columns]

In [10]:
t1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2560 entries, 0 to 2559
Columns: 5272 entries, pr_id to 5270
dtypes: float16(5270), int32(2)
memory usage: 25.8 MB


In [5]:
%%time
store2 = pd.HDFStore('../input/test_resnet_TENSOR.h5')
keys2 = store2.keys()
print('{} tables in storage'.format(len(keys2)))

1 tables in storage
CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 11.9 ms


In [6]:
t2 = store2.select('d0')
t2.head(10)

pr_id  img_num    1             2    3    4         5    6    7         8  \
0     14        0  0.0  0.000000e+00  0.0  0.0  0.000000  0.0  0.0  0.000000   
1     49        0  0.0  0.000000e+00  0.0  0.0  0.000000  0.0  0.0  0.000000   
2     85        0  0.0  5.960464e-08  0.0  0.0  0.000000  0.0  0.0  0.000000   
3     86        0  0.0  3.814697e-06  0.0  0.0  0.000008  0.0  0.0  0.000144   
4     93        0  0.0  0.000000e+00  0.0  0.0  0.000000  0.0  0.0  0.000000   
5     94        0  0.0  2.980232e-07  0.0  0.0  0.000000  0.0  0.0  0.000000   
6     96        0  0.0  2.741814e-06  0.0  0.0  0.000000  0.0  0.0  0.000000   
7     96        1  0.0  9.244680e-05  0.0  0.0  0.000000  0.0  0.0  0.000000   
8     96        2  0.0  2.431870e-05  0.0  0.0  0.000000  0.0  0.0  0.000000   
9    110        0  0.0  2.145767e-06  0.0  0.0  0.000000  0.0  0.0  0.000000   

       ...       5261  5262          5263          5264  5265          5266  \
0      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
1      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
2      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
3      ...        0.0   0.0  0.000000e+00  1.192093e-07   0.0  2.384186e-07   
4      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
5      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
6      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
7      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
8      ...        0.0   0.0  0.000000e+00  0.000000e+00   0.0  0.000000e+00   
9      ...        0.0   0.0  6.556511e-07  0.000000e+00   0.0  1.192093e-07   

   5267      5268          5269          5270  
0   0.0  0.000000  0.000000e+00  0.000000e+00  
1   0.0  0.000000  0.000000e+00  0.000000e+00  
2   0.0  0.000004  2.980232e-07  6.699562e-05  
3   0.0  0.000005  5.960464e-07  8.506775e-03  
4   0.0  0.000000  0.000000e+00  5.960464e-08  
5   0.0  0.000000  0.000000e+00  0.000000e+00  
6   0.0  0.000002  0.000000e+00  3.397465e-06  
7   0.0  0.000002  0.000000e+00  3.159046e-05  
8   0.0  0.000026  1.788139e-07  6.824732e-05  
9   0.0  0.000002  0.000000e+00  6.377697e-06  

[10 rows x 5272 columns]

In [7]:
t2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 256 entries, 0 to 255
Columns: 5272 entries, pr_id to 5270
dtypes: float16(5270), int32(2)
memory usage: 2.6 MB


In [32]:
x2 = np.array(t2.drop(['pr_id', 'img_num'], axis=1, inplace=False).idxmax(axis=1), dtype=np.int)
x2.shape

(256,)

In [11]:
ids = []
for i in range(int(t1.shape[0] / 10)):
        product_id = t1.pr_id.iloc[10*i]
        id_ = int(t1[10*i: 10*i + 10].drop(['pr_id', 'img_num'], axis=1, inplace=False).sum().idxmax())
        ids.append(id_)
x1 = np.array(ids)
print(x1.shape)
x1

(256,)


array([5056, 2480, 3369, 1415, 5056, 2531, 2321, 1047, 1047, 5056, 5056,
       5056, 2488, 1453, 1453, 1453, 1453, 3465, 3336, 5056, 5056, 3244,
        782, 3960, 2593, 1548, 1548, 1548, 1548,  778, 5056, 5056, 5056,
       5056, 3961, 5056, 2531, 5052, 5052, 3247, 3247,  825,  475,  475,
        475,  475, 2409,  707,  785,  785,  785,  199, 2959,  602,  602,
       5056, 1062, 5063, 2593, 1643, 1404, 5056, 5213, 1059, 1059, 1783,
       2593, 2593, 2593, 2593, 1466, 5056,  860,  860, 5068, 5068, 5068,
       5068, 3957, 5056, 5237, 5077, 5077, 1808, 1803, 1803,  457, 2488,
       5056,  807, 5068,   24, 3964, 3409, 5068, 5068, 2531, 2531, 5068,
       5068, 5068, 5068, 2531, 3255, 1761, 3337, 3337, 2531, 2531, 2531,
       1660, 5056, 1995, 5056, 5056, 5056, 5056, 5056, 3212, 5056, 1469,
       5056, 5103, 2521, 2593, 2531, 3046, 2523, 5076, 5076, 5068, 3398,
       3591, 5056, 5056, 1907,  742,  742,  794, 5068, 5068, 5068, 5056,
       2415, 5068, 5068,  860, 5056,  750, 5056,  9

In [34]:
print(x1[:10])
print(x2[:10])

[5056 2480 3369 1415 5056 2531 2321 1047 1047 5056]
[5056 2480 3369 1415 5056 2531 2321 1047 1047 5056]


In [35]:
(x1 ==x2).sum()

256

In [2]:
%%time
inc_store = pd.HDFStore('../input/inception3_test.h5')
print('{} tables in storage'.format(len(inc_store)))

1 tables in storage
CPU times: user 72 ms, sys: 4 ms, total: 76 ms
Wall time: 83.8 ms


In [3]:
ti = inc_store.select('d0')
print(ti.shape)
ti.head()

(256, 5272)


pr_id  img_num             1             2             3             4  \
0     14        0  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
1     49        0  0.000000e+00  1.788139e-07  0.000000e+00  1.788139e-07   
2     85        0  1.788139e-07  2.384186e-07  5.960464e-08  4.768372e-07   
3     86        0  4.589558e-06  4.768372e-07  1.966953e-06  2.706051e-05   
4     93        0  1.370907e-06  5.364418e-07  4.827976e-06  3.457069e-06   

              5             6             7             8      ...       \
0  5.960464e-08  0.000000e+00  0.000000e+00  0.000000e+00      ...        
1  0.000000e+00  5.960464e-08  0.000000e+00  5.960464e-08      ...        
2  4.589558e-06  3.576279e-07  5.960464e-08  1.192093e-07      ...        
3  2.729893e-05  1.430511e-06  1.847744e-06  5.936623e-04      ...        
4  6.556511e-06  1.132488e-06  2.563000e-06  7.748604e-07      ...        

           5261          5262          5263          5264          5265  \
0  0.000000e+00  1.192093e-07  0.000000e+00  0.000000e+00  0.000000e+00   
1  0.000000e+00  1.788139e-07  0.000000e+00  0.000000e+00  0.000000e+00   
2  4.172325e-07  2.980232e-07  2.384186e-07  1.192093e-07  5.960464e-08   
3  4.768372e-06  2.980232e-07  5.185604e-06  2.944469e-05  1.949072e-05   
4  3.457069e-06  4.506111e-05  9.298325e-06  9.536743e-07  1.609325e-06   

           5266          5267      5268          5269          5270  
0  0.000000e+00  0.000000e+00  0.000000  0.000000e+00  5.960464e-08  
1  5.960464e-08  5.960464e-08  0.000000  0.000000e+00  0.000000e+00  
2  1.788139e-07  1.788139e-07  0.000002  7.152557e-07  2.503395e-05  
3  1.430511e-06  2.920628e-05  0.000002  4.172325e-07  4.285574e-05  
4  1.055002e-05  2.443790e-06  0.000003  5.722046e-06  1.978874e-05  

[5 rows x 5272 columns]

In [4]:
xi = np.array(ti.drop(['pr_id', 'img_num'], axis=1, inplace=False).idxmax(axis=1), dtype=np.int)
xi.shape

(256,)

In [7]:
xi[:10]

array([5056, 2480, 3368, 1415, 5056, 2531, 3484, 3484,  240, 5056])

In [15]:
(x1 == xi).sum() / 256.

0.84375